/**
 * Arabic city names for the zones in TIMEZONE_GROUPS (lib/timezone.ts).
 *
 * Intl has no localized city names, and its Arabic zone names are shared by
 * whole regions (Dubai and Muscat are both "توقيت الخليج"), which makes a
 * picker ambiguous. Zones missing here fall back to Intl's zone name, so add a
 * zone here when adding it to TIMEZONE_GROUPS.
 */
export const TIMEZONE_CITIES_AR: Record<string, string> = {
  "Asia/Dubai": "دبي",
  "Asia/Riyadh": "الرياض",
  "Asia/Qatar": "الدوحة",
  "Asia/Kuwait": "الكويت",
  "Asia/Bahrain": "البحرين",
  "Asia/Muscat": "مسقط",
  "Asia/Baghdad": "بغداد",
  "Asia/Tehran": "طهران",
  "Asia/Jerusalem": "القدس",
  "Asia/Beirut": "بيروت",
  "Asia/Amman": "عمّان",
  "Africa/Cairo": "القاهرة",
  "Africa/Nairobi": "نيروبي",
  "Africa/Lagos": "لاغوس",
  "Africa/Johannesburg": "جوهانسبرغ",
  "Africa/Casablanca": "الدار البيضاء",
  "Asia/Kabul": "كابول",
  "Asia/Karachi": "كراتشي",
  "Asia/Kolkata": "كولكاتا",
  "Asia/Colombo": "كولومبو",
  "Asia/Kathmandu": "كاتماندو",
  "Asia/Dhaka": "دكا",
  "Asia/Yangon": "يانغون",
  "Asia/Bangkok": "بانكوك",
  "Asia/Jakarta": "جاكرتا",
  "Asia/Singapore": "سنغافورة",
  "Asia/Kuala_Lumpur": "كوالالمبور",
  "Asia/Manila": "مانيلا",
  "Asia/Hong_Kong": "هونغ كونغ",
  "Asia/Shanghai": "شنغهاي",
  "Asia/Seoul": "سول",
  "Asia/Tokyo": "طوكيو",
  "Europe/London": "لندن",
  "Europe/Dublin": "دبلن",
  "Europe/Lisbon": "لشبونة",
  "Europe/Madrid": "مدريد",
  "Europe/Paris": "باريس",
  "Europe/Brussels": "بروكسل",
  "Europe/Amsterdam": "أمستردام",
  "Europe/Berlin": "برلين",
  "Europe/Zurich": "زيورخ",
  "Europe/Rome": "روما",
  "Europe/Stockholm": "ستوكهولم",
  "Europe/Warsaw": "وارسو",
  "Europe/Athens": "أثينا",
  "Europe/Bucharest": "بوخارست",
  "Europe/Kyiv": "كييف",
  "Europe/Istanbul": "إسطنبول",
  "Europe/Moscow": "موسكو",
  "America/St_Johns": "سانت جونز",
  "America/Halifax": "هاليفاكس",
  "America/New_York": "نيويورك",
  "America/Toronto": "تورونتو",
  "America/Chicago": "شيكاغو",
  "America/Mexico_City": "مكسيكو سيتي",
  "America/Denver": "دنفر",
  "America/Phoenix": "فينيكس",
  "America/Los_Angeles": "لوس أنجلوس",
  "America/Vancouver": "فانكوفر",
  "America/Anchorage": "أنكوريج",
  "Pacific/Honolulu": "هونولولو",
  "America/Bogota": "بوغوتا",
  "America/Lima": "ليما",
  "America/Santiago": "سانتياغو",
  "America/Sao_Paulo": "ساو باولو",
  "America/Argentina/Buenos_Aires": "بوينس آيرس",
  "Australia/Perth": "بيرث",
  "Australia/Adelaide": "أديلايد",
  "Australia/Brisbane": "بريزبن",
  "Australia/Sydney": "سيدني",
  "Pacific/Auckland": "أوكلاند",
  "Pacific/Fiji": "فيجي",
};
